################################################################################
## Texas_Teacher_Comp_TEA.R                                                   ##
## Contact: ian@blincoe.xyz                                                   ##
## R version 3.1.1                                                            ##
## Description: Pull Texas teacher salary information and generate charts of  ##
##   simple comparisons                                                       ##
################################################################################

library(RCurl)

src.dir <- 'C:/Users/blincoeshirey/Documents/Ian/Analysis/Texas-Teacher-Comp'

# Report URL: Everything after the '?' are key-value pairs that are passed to the
# SAS data broker. This particular scheme was generated by completing the web form
# found here: https://rptsvr1.tea.texas.gov/adhocrpt/adpeb.html by selecting the
# 2015-2016 school year, 'Statewide District Totals' as the report type, and
# 'Comma-Delimited File' as the output type. In the URL below, the 'endyear'
# variable can be configured to pull different school years, e.g. 15 for the
# 2014-2015 school year.
url <- 'https://rptsvr1.tea.texas.gov/cgi/sas/broker?_service=marykay&_program=adhoc.addispatch.sas&major=pe&minor=b&linespg=60&charsln=120&selsumm=sd&format=C&endyear=16'

r <- getURL(url, ssl.verifypeer = FALSE)
raw.dat <- read.csv(text = r, skip = 5, stringsAsFactors = FALSE)
raw.dat$Total.Base.Pay <- as.numeric(raw.dat$Total.Base.Pay)
raw.dat$Average.Base.Pay <- as.numeric(raw.dat$Average.Base.Pay)
raw.dat$FTE.Count <- as.numeric(raw.dat$FTE.Count)


# Merge in TEA district classification
district.classification.path <- paste0(src.dir, '/Data/District_Classification_200708_201415.csv')
district.classification <- read.csv(district.classification.path, col.names = c('Name', 'District', 'ClassCode', 'ClassDescription', 'SchoolYear'))
district.classification <- district.classification[district.classification$SchoolYear == '2014-15', ]
raw.dat <- merge(raw.dat, district.classification, by = 'District')


# New set with only teacher staff totals
tot.dat <- raw.dat[raw.dat$Staff == 'TOTAL TEACHING STAFF', ]


# Plot the distribution of teacher counts by district
tot.dat$FTE.Count.Bin <- cut(tot.dat$FTE.Count, breaks = c(0, 100, 1000, Inf), labels = c('Fewer than 100', '100 to 1000', 'More than 1000'))

bin.counts <- table(tot.dat$FTE.Count.Bin)

bin.counts.plot.path <- paste0(src.dir, '/Plots/binCountBarplot.png')
png(file = bin.counts.plot.path, width = 650, height = 350)
bin.counts.plot <- barplot(bin.counts, yaxt = 'n', ylim = c(0, max(bin.counts) * 1.1), col = 'grey40', space = 0.85)
midpoints <- bin.counts.plot
text(x = midpoints[, 1], y = bin.counts + 35, labels = bin.counts)
abline(h = 0)
dev.off()


# Plot the average salary and FTE count for the 'Major Urban' school districts
comp.salary.dat <- tot.dat[tot.dat$ClassDescription == 'MAJOR URBAN', c(5, 8, 9, 10)]
comp.salary.dat <- comp.salary.dat[order(-comp.salary.dat$FTE.Count), ]

comp.salary.top.five.mu.dat <- comp.salary.dat[1:5, c(1, 4)]
comp.salary.rest.mu.dat <- c('Other Major Urban',
                             sum(comp.salary.dat$Total.Base.Pay[6:nrow(comp.salary.dat)]) / sum(comp.salary.dat$FTE.Count[6:nrow(comp.salary.dat)]))
comp.salary.all.ms.dat <- c('All Major Suburban',
                           sum(tot.dat$Total.Base.Pay[tot.dat$ClassDescription == 'MAJOR SUBURBAN']) / sum(tot.dat$FTE.Count[tot.dat$ClassDescription == 'MAJOR SUBURBAN']))

comp.salary.dat <- rbind(comp.salary.top.five.mu.dat,
                         comp.salary.rest.mu.dat,
                         comp.salary.all.ms.dat,
                         rep(NA, 2))

comp.salary.dat$Average.Base.Pay <- as.numeric(comp.salary.dat$Average.Base.Pay)

statewide.average <- sum(tot.dat$Total.Base.Pay) / sum(tot.dat$FTE.Count)

avg.salary.plot.names <- c('Houston\n ISD', 'Dallas\n ISD', 'Northside\n ISD', 'Austin\n ISD', 'Ft. Worth\n ISD', 'Oth. Major\n Urban', 'All Major\n Suburban', '')

avg.salary.plot.path <- paste0(src.dir, '/Plots/AverageSalaryBarplot.png')
png(file = avg.salary.plot.path, width = 650, height = 350)
avg.salary.plot <- barplot(comp.salary.dat$Average.Base.Pay,
                           yaxt = 'n', names.arg = avg.salary.plot.names,
                           ylim = c(0, max(comp.salary.dat$Average.Base.Pay[!is.na(comp.salary.dat$Average.Base.Pay)]) * 1.1),
                           col = 'grey40', space = 0.65)

midpoints <- avg.salary.plot
text(x = midpoints[, 1],
     y = comp.salary.dat$Average.Base.Pay + 2000,
     labels = paste0(sprintf('$%.1f', comp.salary.dat$Average.Base.Pay / 1000), 'K'))
abline(h = 0)
abline(h = statewide.average, lty = 2)
statewide.average.label <- paste0('Statewide\n Average\n (',
                                  sprintf('$%.1f', statewide.average / 1000),
                                  'K)')
text(x = 12.6, y = statewide.average - 6000, labels = statewide.average.label)

dev.off()



